spring:
  application:
    name: registryService

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      uri: http://localhost:8888
      name: RegistryService

server:
  port:
    8761
  wait-time-in-ms-when-sync-empty: 0
  wait-time-in-ms: 500

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  #  instance:
  #   prefer-ip-address:false  #for docker to work set to true